### Options
OPTIONS {{u}}/darts
###

POST {{u}}/darts
Content-Type: application/json

{
  "module": "cowsay",
  "version": "v0.1.3",
  "inputs": {
    "Message": "Hi from vite dev "
  }
}
###
POST {{u}}/darts
Authorization: Bearer {{REST_WALLET}}
Content-Type: application/json

{
  "module": "cowsay",
  "version": "v0.1.3",
  "inputs": {
    "Message": "Hi from vite dev "
  }
}
###

POST {{u}}/darts
Content-Type: application/json

{
  "module": "nearai",
  "version": "v0.3.0",
  "inputs": {
    "Prompt": "Beautiful girl \n amongst european graduates",
    "Seed": "{{$randomInt 1 10000000}}"
  }
}
###

POST {{u}}/darts
Content-Type: application/json

{
  "module": "nearai",
  "version": "v0.4.1",
  "inputs": {
    "Prompt": "An image depicting the serenity of inner peace in a busy world. At the top: \"How to Be Good at Inner Peace\" is in bold font, with \"How to Be Good At\" on all one line, and \"Inner Peace\" on its own line as a huge modern sans serif font prominently placed in the upper half of the design. At the bottom: \"Michelle Volz, LMFT\" as the author's name.",
    "Seed": "{{$randomInt 1 10000000}}",
    "N": 4
  }
}
###

POST {{u}}/darts
Content-Type: application/json

{
  "module": "nearai",
  "version": "v0.4.1",
  "inputs": {
    "Prompt": "note-taking app interface\"",
    "Seed": "{{$randomInt 1 10000000}}",
    "N": 4
  }
}
###

POST {{u}}/creations
Authorization: Bearer {{REST_WALLET}}
Content-Type: application/json

{
  "module": "github.com/darts2024/dart-isdxl",
  "version": "v1.6.0",
  "inputs": {
    "Prompt": "Beautiful girl",
    "Device": "xpu",
    "Seed": "{{$randomInt 1 10000000}}"
  }
}