# Darts
POST http://ideomind-git-bug-darts-not-found-decenter-ai.vercel.app/darts
Content-Type: application/json

{}

HTTP/1.0 308  - Permanent Redirect
content-type: text/plain
location: https://ideomind-git-bug-darts-not-found-decenter-ai.vercel.app/darts
refresh: 0;url=https://ideomind-git-bug-darts-not-found-decenter-ai.vercel.app/darts
server: Vercel

HTTP/1.1 500  - Internal Server Error
cache-control: public, max-age=0, must-revalidate
content-length: 186
content-type: application/json
date: Sat, 30 Nov 2024 06:30:52 GMT
server: Vercel
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-robots-tag: noindex
x-vercel-cache: MISS
x-vercel-id: bom1::iad1::5pw5p-1732948252707-ad3ec4eefc08
connection: close
###

POST http://localhost:5173/darts
Content-Type: application/json

{
  "module": "isdxl",
  "version": "v0.3.0",
  "inputs": {
    "Prompt": "mind dreaming of a futuristic aircraft",
    "Seed": "40",
    "Device": "xpu"
  }
}

HTTP/1.1 200  - OK
access-control-allow-origin: *
content-length: 690
content-type: application/json
date: Sat, 30 Nov 2024 05:35:17 GMT
connection: close
###

POST http://localhost:5173/darts
Content-Type: application/json

{
  "module": "github.com/darts2024/dart-isdxl",
  "version": "v0.3.0",
  "inputs": {
    "Prompt": "Beautiful girl",
    "Device": "xpu"
  }
}

HTTP/1.1 200  - OK
access-control-allow-origin: *
content-length: 677
content-type: application/json
date: Sat, 30 Nov 2024 05:34:12 GMT
connection: close