name: Build

on:
  push:
    branches:
      - main

    tags:
      - "*"
  pull_request:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          check-latest: false

      - name: Install Dependencies
        run: |
          cp .env.example .env
          bun i

      - name: Build
        run: |
          bun run build
