name: Build

on:
  push:
    branches:
      - main

    tags:
      - "*"
  pull_request:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          check-latest: false
          cache-dependency-path: "bun.lockb"
          cache: "npm"

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        timeout-minutes: 360

      - name: Write environment
        run: |
          echo "$envfile" > .env
          sed -i 's/ /\n/g' .env
          # source .env

      - name: Install Dependencies
        run: |
          cp .env.example .env.local
          bun i

      - name: Build
        run: |
          bun run build
